version: '3.8'

services:
  app:
    image: ghcr.io/jasonraimondi/opnsense_quick_manager
    build: .
    ports:
      - "8000:8000"
    environment:
      OPNSENSE_HOST: "https://opnsense.raimondi.dev"
      OPNSENSE_API_SECRET: ${OPNSENSE_API_SECRET}
      OPNSENSE_API_KEY: ${OPNSENSE_API_KEY}
